### PR TITLE
update to coq-8.10.2

### PR DESCRIPTION
**Pull request by btj**

### CODE REVIEW

**Comment by robbertkrebbers** [comment]
Looks mostly good to me.

Small comment, for `Set Refine Instance Mode.` it might make sense to add `Local`. Then we're sure it does not set the option globally. AFAIK in recent versions of Coq they started to make `Global`/`Local` required everywhere.

**Comment by robbertkrebbers** [comment]
And forgot to say: Thanks!

**Comment by btj** [comment]
I am working on an update to coq-8.11.2 now. This version no longer supports `Set Refine Instance Mode` (it supports the new syntax `#[refine] Instance` instead), so these are going away anyway. So if you prefer, you can wait to merge this until I'm done with this.

**Comment by robbertkrebbers** [comment]
Sounds good to me.

**Comment by robbertkrebbers** [comment]
I noticed too late that the PR forgot to update the Coq version in the README. I just pushed a fix for that https://github.com/robbertkrebbers/ch2o/commit/532314e74f5f4cee02ad471cad3428e00cc4d782

**Pull request merged**
